baseURL = 'https://ralcaniz.dev/'
defaultContentLanguage = 'es'
title = 'De Reparto a Root'
theme = 'PaperMod'

[params]
  author = "Rubén Alcañiz"
  description = "De camionero a desarrollador: aprendiendo Linux y programación desde cero."
